global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ["prometheus:9090"]

  # - job_name: 'node'
  #   static_configs:
  #     - targets: ["node_exporter:9100"]

  - job_name: 'dcgm'
    static_configs:
    - targets: ['dcgm_exporter:9400']

  # - job_name: 'grafana'
  #   static_configs:
  #     - targets: ["grafana:3000"]
